---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - eda:
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Say Hello
      condition: true
      action:
        debug:
          msg: "{{ event }}"
